version: '3'

dotenv: ['.env']

tasks:
  default:
    cmds:
      - go run .
  single-test:
    cmds:
      - go test --count=1 -v . -run {{.CLI_ARGS}}
  single-test-gossip:
    cmds:
      - go test --count=1 -v ./gossip -run {{.CLI_ARGS}}
  proto:
    cmds:
       - protoc --go_out=. --go_opt=paths=source_relative
        --twirp_out=. -I=./ pb/*.proto
    silent: true
