version: '3'

dotenv: ['.env']

tasks:
  default:
    cmds:
      - GOMAXPROCS=1 go run .
  single-test:
    cmds:
      - GOMAXPROCS=1 go test --count=1 -v . -run {{.CLI_ARGS}}
  single-test-gossip:
    cmds:
      - GOMAXPROCS=1 go test --count=1 -v ./gossip -run {{.CLI_ARGS}}
  proto:
    cmds:
       - protoc --go_out=. --go_opt=paths=source_relative
        --go-grpc_out=. --go-grpc_opt=paths=source_relative
        -I=./ pb/*.proto
    silent: true
